### ISSUE TITLE
Errors deoloying spring-music as an example

### ISSUE THREAD

**Issue by rayh0001** [BarDweller/spring-cloud-connectors-icd#1]
Hello,

I tried following the instructions using the spring-music sample: https://github.com/cloudfoundry-samples/spring-music . I used the following gradle file :
```
plugins {
	id 'org.springframework.boot' version '2.1.2.RELEASE'
	id 'java'
	id 'war'
}

apply plugin: 'io.spring.dependency-management'

version = '1.0'

group = 'org.cloudfoundry.samples.music'
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    jcenter()
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
    maven { url "https://repo.spring.io/plugins-release" }
	maven { url "https://jitpack.io" }
}

ext {
	set('springCloudVersion', 'Greenwich.RELEASE')
}


dependencies {
	compile 'com.github.bardweller:spring-cloud-connectors-icd:v0.1'
	
	implementation 'org.springframework.boot:spring-boot-starter-cloud-connectors'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-starter'
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'
	runtimeOnly 'mysql:mysql-connector-java'
	runtimeOnly 'org.postgresql:postgresql'

    // Webjars
    compile "org.webjars:bootstrap:3.1.1"
    compile "org.webjars:angularjs:1.2.16"
    compile "org.webjars:angular-ui:0.4.0-2"
    compile "org.webjars:angular-ui-bootstrap:0.10.0-1"
    compile "org.webjars:jquery:2.1.0-2"

	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

war {
    enabled = true
    from 'src/rootContent' // adds a file-set to the root of the archive
}
```

Built, pushed and binded it to an ICD Postgrs instance, restaged and I get the following error:
```
   2019-03-18T17:25:14.09-0600 [STG/0] OUT -----> Downloading Auto Reconfiguration 1.12.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.12.0_RELEASE.jar (0.1s)
   2019-03-18T17:25:14.09-0600 [STG/0] OUT -----> Retrieving com.ibm.ws.liberty-18.0.0.4-201902232128.tar.gz ... (0.0s)
   2019-03-18T17:25:14.81-0600 [STG/0] OUT          Installing archive ... (0.7s)
   2019-03-18T17:25:14.89-0600 [STG/0] ERR E, [2019-03-18T23:25:14.896545 #34] ERROR -- /tmp/buildpacks/b5d747b1589ee5dcf0db61eeac90a265/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: Resource dev-icd-support-postgres does not contain a cloud.services.dev-icd-support-postgres.connection.uri property>
   2019-03-18T17:25:14.89-0600 [STG/0] ERR Resource dev-icd-support-postgres does not contain a cloud.services.dev-icd-support-postgres.connection.uri property
   2019-03-18T17:25:14.90-0600 [STG/0] ERR Failed to compile droplet: Failed to compile droplet: exit status 1
   2019-03-18T17:25:14.92-0600 [STG/0] OUT Exit status 223
   2019-03-18T17:25:15.32-0600 [STG/0] OUT Cell 97eb0825-842d-44a6-990d-609b3bbfee97 stopping instance 78a9bf4e-9353-464a-b4bf-ba81ec226492
   2019-03-18T17:25:15.32-0600 [STG/0] OUT Cell 97eb0825-842d-44a6-990d-609b3bbfee97 destroying container for instance 78a9bf4e-9353-464a-b4bf-ba81ec226492
   2019-03-18T17:25:16.13-0600 [STG/0] OUT Cell 97eb0825-842d-44a6-990d-609b3bbfee97 successfully destroyed container for instance 78a9bf4e-9353-464a-b4bf-ba81ec226492
```

**Comment by BarDweller** [comment]
Hi.. which buildpack is this? It doesn't look like it's even getting to the point where code is running.. as if something in the buildpack is looking for old format credentials. 
(I tested with Java buildpack)

**Comment by rayh0001** [comment]
Hi @BarDweller, it was the liberty for Java, it seems the default for IBM Cloud. Is this as simple as pushing the app (ic cf push -b java_buildpack)...?

**Comment by rayh0001** [comment]
I attempted `ic cf push -b java_buildpack` and got the following:

```
   2019-03-19T10:24:23.97-0600 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx404242K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=132333K
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT   .   ____          _            __ _ _
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT  =========|_|==============|___/=/_/_/_/
   2019-03-19T10:24:29.79-0600 [APP/PROC/WEB/0] OUT  :: Spring Boot ::        (v2.0.1.RELEASE)
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 2019-03-19 16:24:31.900 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_202]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_202]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.getUri(UriInfo.java:97) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.<init>(UriInfo.java:50) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.StandardUriInfoFactory.createUri(StandardUriInfoFactory.java:17) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.UriBasedServiceInfo.<init>(UriBasedServiceInfo.java:26) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.RelationalServiceInfo.<init>(RelationalServiceInfo.java:22) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-19T10:24:31.90-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.PostgresqlServiceInfo.<init>(PostgresqlServiceInfo.java:20) ~[spring_auto
```

**Comment by BarDweller** [comment]
Testing this at the mo. 

Initial tests resulted in a working Spring Music running against Postgresql ICD. 

My approach.
`git clone https://github.com/cloudfoundry-samples/spring-music.git`
`cd spring-music`
edit `build.gradle` :
- add jitpack repo into root level repositories block around line 31.
```
repositories {
    mavenCentral()
    mavenLocal()
    maven { url "https://jitpack.io" }
}
```
- add dependency to dependencies section. 
```
dependencies {
    compile "com.github.bardweller:spring-cloud-connectors-icd:v0.1"

    // Spring Boot
   ...
```

`./gradlew clean build assemble`
`ic cf push MyTestAppName -p ./build/libs/spring-music-1.0.jar -b java_buildpack`

wait for push to complete, check locks with `ic cf logs MyTestAppName --recent`

(Note I do see an exception from Hibernate about PgConnection.createClob not being implemented, but it's ignorable, the app comes up fine, the underlying issue seems related to versions of postgres driver / hibernate & spring boot used)

So, either the way you are building the app is breaking this all somehow, or your binding is somehow odd. The (partial) stack trace pasted hints that the Uri being used to create an instance of PostgresqlServiceInfo is null, I'd love to see the next few lines of that stack trace, as they could be quite informative. 

The ServiceInfoCreator registered by this repo tests to see if the uri it would use is null, and declines to get involved in processing if so. So I'm guessing that the next few lines would show the original spring code trying to parse the binding (although I'm also not sure why as the label etc shouldn't match well for that). 

I may need to see a sanitised version of your VCAP_SERVICES to understand what's going on here.. I'll see if I can't get the code I have in this repo to log that to stdout to be helpful.

**Comment by rayh0001** [comment]
Thanks again @BarDweller. Followed the same steps, but I bound the app to the ICD service 
`ibmcloud cf bind-service spring-music dev-icd-postgres` and then restged, and saw this in the log:
```
   2019-03-20T11:56:53.61-0600 [API/9] OUT Process has crashed with type: "web"
   2019-03-20T11:56:53.63-0600 [API/9] OUT App instance exited with guid 1dae3317-f4d2-4f76-9aa6-e6a588e8dead payload: {"instance"=>"a72bc84e-055b-4745-5cfd-45b6", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>2, "crash_timestamp"=>1553104613581636677, "version"=>"4138984e-cab5-48d7-8d98-07e8b7a0d06b"}
   2019-03-20T11:56:53.64-0600 [CELL/0] OUT Cell da3faca7-0d84-40bb-9b43-843e8026ce2a stopping instance a72bc84e-055b-4745-5cfd-45b6
   2019-03-20T11:56:53.64-0600 [CELL/0] OUT Cell da3faca7-0d84-40bb-9b43-843e8026ce2a destroying container for instance a72bc84e-055b-4745-5cfd-45b6
   2019-03-20T11:56:54.12-0600 [PROXY/0] OUT Exit status 137
   2019-03-20T11:56:54.34-0600 [CELL/0] OUT Cell 57a203b6-54f0-43b0-8a23-ac1f11ae386b creating container for instance d2703f36-1917-4a11-4b9b-19fd
   2019-03-20T11:56:55.56-0600 [CELL/0] OUT Cell da3faca7-0d84-40bb-9b43-843e8026ce2a successfully destroyed container for instance a72bc84e-055b-4745-5cfd-45b6
   2019-03-20T11:56:56.19-0600 [CELL/0] OUT Cell 57a203b6-54f0-43b0-8a23-ac1f11ae386b successfully created container for instance d2703f36-1917-4a11-4b9b-19fd
   2019-03-20T11:56:58.93-0600 [CELL/0] OUT Starting health monitoring of container
   2019-03-20T11:56:59.56-0600 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx404242K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=132333K
   2019-03-20T11:57:04.28-0600 [APP/PROC/WEB/0] OUT   .   ____          _            __ _ _
   2019-03-20T11:57:04.28-0600 [APP/PROC/WEB/0] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
   2019-03-20T11:57:04.28-0600 [APP/PROC/WEB/0] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
   2019-03-20T11:57:04.28-0600 [APP/PROC/WEB/0] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
   2019-03-20T11:57:04.28-0600 [APP/PROC/WEB/0] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
   2019-03-20T11:57:04.28-0600 [APP/PROC/WEB/0] OUT  =========|_|==============|___/=/_/_/_/
   2019-03-20T11:57:04.29-0600 [APP/PROC/WEB/0] OUT  :: Spring Boot ::        (v2.0.1.RELEASE)
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 2019-03-20 17:57:05.898 ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application run failed
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_202]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_202]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.getUri(UriInfo.java:97) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.<init>(UriInfo.java:50) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.StandardUriInfoFactory.createUri(StandardUriInfoFactory.java:17) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.UriBasedServiceInfo.<init>(UriBasedServiceInfo.java:26) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.RelationalServiceInfo.<init>(RelationalServiceInfo.java:22) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.PostgresqlServiceInfo.<init>(PostgresqlServiceInfo.java:20) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.PostgresqlServiceInfoCreator.createServiceInfo(PostgresqlServiceInfoCreator.java:21) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.PostgresqlServiceInfoCreator.createServiceInfo(PostgresqlServiceInfoCreator.java:13) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.RelationalServiceInfoCreator.createServiceInfo(RelationalServiceInfoCreator.java:74) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.RelationalServiceInfoCreator.createServiceInfo(RelationalServiceInfoCreator.java:15) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfo(AbstractCloudConnector.java:61) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfos(AbstractCloudConnector.java:40) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceInfos(Cloud.java:89) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getCloudProperties(Cloud.java:256) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.CloudPropertySourceApplicationContextInitializer.lambda$initialize$1(CloudPropertySourceApplicationContextInitializer.java:50) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.AbstractCloudHolder.withCloud(AbstractCloudHolder.java:41) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.reconfiguration.CloudPropertySourceApplicationContextInitializer.initialize(CloudPropertySourceApplicationContextInitializer.java:47) ~[spring_auto_reconfiguration-2.7.0_RELEASE.jar!/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:633) ~[spring-boot-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) ~[spring-boot-2.0.1.RELEASE.jar!/:2.0.1.RELEASE]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.samples.music.Application.main(Application.java:16) [classes/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
   2019-03-20T11:57:05.93-0600 [APP/PROC/WEB/0] OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
   2019-03-20T11:57:06.06-0600 [APP/PROC/WEB/0] OUT Exit status 1
   2019-03-20T11:57:06.10-0600 [CELL/SSHD/0] OUT Exit status 0
   2019-03-20T11:57:11.51-0600 [CELL/0] OUT Cell 57a203b6-54f0-43b0-8a23-ac1f11ae386b stopping instance d2703f36-1917-4a11-4b9b-19fd
   2019-03-20T11:57:11.54-0600 [API/21] OUT Process has crashed with type: "web"
   2019-03-20T11:57:11.55-0600 [API/21] OUT App instance exited with guid 1dae3317-f4d2-4f76-9aa6-e6a588e8dead payload: {"instance"=>"d2703f36-1917-4a11-4b9b-19fd", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>3, "crash_timestamp"=>1553104631459971024, "version"=>"4138984e-cab5-48d7-8d98-07e8b7a0d06b"}
   2019-03-20T11:57:11.51-0600 [CELL/0] OUT Cell 57a203b6-54f0-43b0-8a23-ac1f11ae386b destroying container for instance d2703f36-1917-4a11-4b9b-19fd
   2019-03-20T11:57:11.77-0600 [PROXY/0] OUT Exit status 137
   2019-03-20T11:57:12.42-0600 [CELL/0] OUT Cell 57a203b6-54f0-43b0-8a23-ac1f11ae386b successfully destroyed container for instance d2703f36-1917-4a11-4b9b-19fd

```

**Comment by BarDweller** [comment]
For some reason, it looks like the Spring Cloud Connectors (SCC) core code is trying to handle your service binding, before the extension code I've written gets to do so. 

Based on a little guesswork and some other info ;) .. I suspect your service has some non default tags added to it that are confusing SCC and causing it to try to handle the service itself. Double check & remove any 'postgres' or 'postgresql' tags on the service =) My service only has the following.. 
```
        "data_management",
        "ibm_created",
        "rc_compatible",
        "ibmcloud-alias"
```

**Comment by rayh0001** [comment]
We've noticed this earlier in comparison to compose postgres, psotgres,psotgresql are always there by default. What's the best way to remove?

**Comment by BarDweller** [comment]
I have allocated Databases for Postgresql, Databases for MongoDB, and Databases for Redis all to check behavior for this.. and the tags for all of them are only the 4 tags as above.  So I don't understand how yours has the extra tags. Their presence effectively states to SCC that the service info is formatted as expected for that type of service, which it isn't, which leads to the issue you're seeing at the mo there. 

At a guess (I've not had to do this myself, so it's untested!), based on the info at https://cli.cloudfoundry.org/en-US/cf/update-service.html  .. it looks like you might be able to use `cf update-service myServiceName -t "data_management, ibm_created, rc_compatible, ibmcloud-alias"` to set the tags as just the 4 above. 

I'm working on the successor to this repo, which will handle Redis/MongoDB/Postgres with per-connection ssl configuration, but unlike this repo, it won't work unchanged with Spring-Music. Sadly Spring-Music contains code that is aware of the implementation detail for SCC, and although the current postgres approach is able to stay within that by re-using SCC classes, that won't work for Redis or Mongo (as they have no filesystem based way to set a trusted cert).

For any normal app (ie, not Spring Music, which is actively aware of SCC implementation details, and using them to determine which of many db profiles it finds itself running against), this won't be a problem, and the new repo will work fine.

**Comment by rayh0001** [comment]
Apologies for late response ozzy.  That did the trick, I don't see the issue of connecting to postgres anymore.  Much obliged.
